"""add price_at_add to order_items

Revision ID: 819cce996301
Revises: daca523f69f5
Create Date: 2026-08-15 13:31:20.404661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819cce996301'
down_revision: Union[str, Sequence[str], None] = 'daca523f69f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds OrderItem.price_at_add, a copy of Dish.price captured at insert
    time so a later price change never retroactively changes an already-open
    Order's total.

    The column is added with a temporary server_default, which is then dropped,
    rather than added bare as NOT NULL. The table is empty the first time this
    runs, but it will not be on a re-run: downgrade drops the column, so a
    downgrade/upgrade cycle on a database that already has order items would
    otherwise fail on a NOT NULL violation, and entrypoint.sh runs
    `alembic upgrade head` on every container start. Dropping the default
    afterwards keeps the ORM the only thing that decides this value, so no
    insert can silently record a zero price.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_items',
        sa.Column('price_at_add', sa.Numeric(precision=8, scale=2), nullable=False, server_default='0'),
    )
    op.alter_column('order_items', 'price_at_add', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_at_add')
    # ### end Alembic commands ###
