"""add price_at_add to order_items

Revision ID: 819cce996301
Revises: daca523f69f5
Create Date: 2026-08-15 13:31:20.404661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819cce996301'
down_revision: Union[str, Sequence[str], None] = 'daca523f69f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds OrderItem.price_at_add (AD-7), a copy of Dish.price captured at insert
    time so a later price change never retroactively changes an already-open
    Order's total. No server_default: no story before this one ever inserts an
    OrderItem row, so this table is empty in every environment this runs against.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price_at_add', sa.Numeric(precision=8, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'price_at_add')
    # ### end Alembic commands ###
