"""Add case-insensitive unique index on ingredient name

Revision ID: daca523f69f5
Revises: f1743862f1b1
Create Date: 2026-08-11 22:36:45.642385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daca523f69f5'
down_revision: Union[str, Sequence[str], None] = 'f1743862f1b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Adds a functional unique index so two ingredient names differing only by
    case cannot coexist. The plain UNIQUE constraint on the column stays: it
    is what the ORM model declares, and this index is strictly stronger
    rather than a replacement. Mirrors f1743862f1b1's identical fix for
    User.username.

    Note: this fails if two existing rows already differ only by name case.
    That is correct, those rows are the ambiguity being closed, and they have
    to be reconciled by hand before upgrading.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_ingredients_name_lower', 'ingredients', [sa.literal_column('lower(name)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_ingredients_name_lower', table_name='ingredients')
    # ### end Alembic commands ###
