"""add dish source_suggestion_id and ai_recipe_suggestions dismissed

Revision ID: f9cbd3ff5b87
Revises: 856ef9ffb5cd
Create Date: 2026-08-22 13:52:17.269586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cbd3ff5b87'
down_revision: Union[str, Sequence[str], None] = '856ef9ffb5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Trap 22: a NOT NULL column add with no server_default breaks against any existing row
    # (confirmed against this dev DB, which already has rows from Story 6.1's own manual
    # testing). server_default backfills every existing row to False; new rows still go
    # through the ORM's own Python-side default=False on top of this.
    op.add_column(
        'ai_recipe_suggestions',
        sa.Column('dismissed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('dishes', sa.Column('source_suggestion_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'dishes', 'ai_recipe_suggestions', ['source_suggestion_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'source_suggestion_id')
    op.drop_column('ai_recipe_suggestions', 'dismissed')
    # ### end Alembic commands ###
