"""add dish source_suggestion_id and ai_recipe_suggestions dismissed

Revision ID: f9cbd3ff5b87
Revises: 856ef9ffb5cd
Create Date: 2026-08-22 13:52:17.269586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9cbd3ff5b87'
down_revision: Union[str, Sequence[str], None] = '856ef9ffb5cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # A NOT NULL column add with no server_default breaks against any existing row
    # (confirmed against a dev DB that already had suggestion rows in it).
    # server_default backfills every existing row to False; new rows still go
    # through the ORM's own Python-side default=False on top of this.
    op.add_column(
        'ai_recipe_suggestions',
        sa.Column('dismissed', sa.Boolean(), nullable=False, server_default=sa.text('false')),
    )
    op.add_column('dishes', sa.Column('source_suggestion_id', sa.Integer(), nullable=True))
    # Named explicitly: autogenerate emitted an unnamed constraint here,
    # which Postgres itself names on creation but which downgrade()'s drop_constraint(None, ...)
    # cannot target — confirmed via `alembic downgrade --sql`, which raised
    # `CompileError: Can't emit DROP CONSTRAINT ... it has no name`. Matches the name Postgres's
    # own default naming already assigned, so no live database is affected by this rename.
    op.create_foreign_key(
        'dishes_source_suggestion_id_fkey', 'dishes', 'ai_recipe_suggestions', ['source_suggestion_id'], ['id']
    )
    # Unique, not just indexed: closes a TOCTOU race where two concurrent
    # `POST /api/menu/dishes` requests citing the same suggestion could both pass
    # MenuService._validate_source_suggestion's unlocked SELECT before either commits, giving one
    # suggestion two confirming Dishes. Postgres permits multiple NULLs under a plain UNIQUE
    # constraint, so every Dish with no suggestion is unaffected.
    op.create_unique_constraint(
        'uq_dishes_source_suggestion_id', 'dishes', ['source_suggestion_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_dishes_source_suggestion_id', 'dishes', type_='unique')
    op.drop_constraint('dishes_source_suggestion_id_fkey', 'dishes', type_='foreignkey')
    op.drop_column('dishes', 'source_suggestion_id')
    op.drop_column('ai_recipe_suggestions', 'dismissed')
    # ### end Alembic commands ###
