"""add dish_id and suggestion_id to ai_chat_sessions

Revision ID: ff8b89322b7c
Revises: f9cbd3ff5b87
Create Date: 2026-08-26 16:46:06.035367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff8b89322b7c'
down_revision: Union[str, Sequence[str], None] = 'f9cbd3ff5b87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_chat_sessions', sa.Column('dish_id', sa.Integer(), nullable=True))
    op.add_column('ai_chat_sessions', sa.Column('suggestion_id', sa.Integer(), nullable=True))
    # Named explicitly (this exact migration shape has already tripped this once):
    # autogenerate emits an unnamed constraint here, which Postgres
    # itself names on creation but which downgrade()'s drop_constraint(None, ...) cannot target.
    # Matches the name Postgres's own default naming convention already assigns
    # (<table>_<column>_fkey), so no live database is affected by this rename.
    op.create_foreign_key(
        'ai_chat_sessions_dish_id_fkey', 'ai_chat_sessions', 'dishes', ['dish_id'], ['id']
    )
    op.create_foreign_key(
        'ai_chat_sessions_suggestion_id_fkey',
        'ai_chat_sessions',
        'ai_recipe_suggestions',
        ['suggestion_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_chat_sessions_suggestion_id_fkey', 'ai_chat_sessions', type_='foreignkey')
    op.drop_constraint('ai_chat_sessions_dish_id_fkey', 'ai_chat_sessions', type_='foreignkey')
    op.drop_column('ai_chat_sessions', 'suggestion_id')
    op.drop_column('ai_chat_sessions', 'dish_id')
    # ### end Alembic commands ###
